# Generated by Django 2.2.6 on 2020-06-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoadon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadon',
            name='TongTien',
            field=models.IntegerField(default=0, verbose_name='Tổng tiền'),
        ),
    ]
