# Generated by Django 2.2.6 on 2020-06-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucTinTuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.CharField(max_length=500, null=True, verbose_name='Tên danh mục tin tức')),
                ('DuongDan', models.SlugField(default='', max_length=100, verbose_name='Đường dẫn')),
            ],
            options={
                'verbose_name_plural': 'Danh mục tin tức',
            },
        ),
        migrations.CreateModel(
            name='TinTuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.TextField(null=True, verbose_name='Tiêu đề')),
                ('MoTaNgan', models.TextField(null=True, verbose_name='Mô tả ngắn')),
                ('NoiDung', models.TextField(null=True, verbose_name='Nội dung')),
                ('Anh', models.ImageField(default='product-default.jpg', upload_to='', verbose_name='Ảnh')),
                ('NgayTao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('DuongDan', models.SlugField(default='', max_length=200, verbose_name='Đường dẫn')),
                ('LoaiTinTuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.DanhMucTinTuc', verbose_name='Danh mục tin tức')),
            ],
            options={
                'verbose_name_plural': 'Tin tức',
            },
        ),
    ]
