# Generated by Django 2.2.6 on 2020-06-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='luotxem',
            field=models.IntegerField(default=1),
        ),
    ]
