# Generated by Django 2.2.6 on 2020-06-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0002_sanpham_luotxem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhamang',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='simtheogia',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tiêu đề'),
        ),
    ]
