# Generated by Django 2.2.6 on 2020-06-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongthuy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namsinh',
            name='namsinh',
            field=models.IntegerField(unique=True, verbose_name='Năm sinh'),
        ),
    ]
