# Generated by Django 3.0.6 on 2020-06-09 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sanpham', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaytao', models.DateField(auto_now_add=True)),
                ('TongTien', models.FloatField(default=0, verbose_name='Tổng tiền')),
                ('SanPhams', models.ManyToManyField(blank=True, to='sanpham.SanPham', verbose_name='Danh sách sản phẩm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đặt')),
            ],
            options={
                'verbose_name_plural': 'Giỏ hàng',
            },
        ),
        migrations.CreateModel(
            name='CTGH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DonGia', models.IntegerField(default=0, verbose_name='Giá')),
                ('GH', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='giohang.GioHang', verbose_name='Giỏ hàng')),
                ('SP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sanpham.SanPham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name_plural': 'Chi tiết giỏ hàng',
            },
        ),
    ]
