# Generated by Django 2.2.6 on 2020-06-10 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DauGia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayHetHan', models.DateTimeField(verbose_name='Ngày hết hạn')),
                ('GiaMuaLuon', models.FloatField(verbose_name='Giá mua luôn')),
                ('GiaHienTai', models.FloatField(default=0, verbose_name='Giá hiện tại')),
                ('DuongDan', models.SlugField(default='', max_length=100)),
                ('DaDauGia', models.BooleanField(default=False, verbose_name='Đã đấu giá')),
                ('NguoiDauGiaHienTai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đấu giá hiện tại')),
                ('Sim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sanpham.SanPham', verbose_name='Sim đấu giá')),
            ],
            options={
                'verbose_name_plural': 'Đấu giá',
            },
        ),
    ]
