# Generated by Django 2.2.6 on 2020-06-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DauGia', '0002_daugia_giatoithieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='daugia',
            name='luotxem',
            field=models.IntegerField(default='1'),
        ),
    ]
