# Generated by Django 2.2.6 on 2020-06-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DauGia', '0003_daugia_luotxem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daugia',
            name='GiaHienTai',
            field=models.IntegerField(default=0, verbose_name='Giá hiện tại'),
        ),
        migrations.AlterField(
            model_name='daugia',
            name='GiaMuaLuon',
            field=models.IntegerField(verbose_name='Giá mua luôn'),
        ),
        migrations.AlterField(
            model_name='daugia',
            name='GiaToiThieu',
            field=models.IntegerField(default=0, verbose_name='Giá tối thiểu'),
        ),
    ]
